---
title: "5. Fitting Yield Curves"
author: "Alexis Sciau"
date: "08/04/2020"
output:
  html_document:
    code_folding: hide
    df_print: kable
    theme: default
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading libraries, echo=TRUE, message=FALSE}
library(data.table)
library(lubridate)
library(ggplot2)
library(pracma)
theme_set(theme_minimal())
```

## 5.1 Getting started
Though we do not have access to the same data as the book, ie a collection of US Treasury bond yields as at 29 May 2009, we retrieve from the [US treasury website](https://www.google.com "Daily Treasury Yield Curve Rates  from US Treasury") the daily treasury yield curve rates. Plotting this curve, we expect to get something close to the fig 5.2.

```{r US_yield_curve_example}
yc_dt <- fread("../data/data_YC_US")
yc_dt[,index:=fastPOSIXct(index)]
yc_dt[,index:=as.Date(index)]
yc_xts <- as.xts(yc_dt)

tenors <- c(1/12,2/12,3/12,6/12,1,2,3,5,7,10,20,30)
colnames(yc_xts)<-tenors


rates <- yc_xts["20090528/20090603"]

daily_data <- as.data.table(melt(as.data.table(rates), measure.vars = colnames(rates)))
daily_data[,index_f := as.factor(index)]
ggplot(daily_data,aes(x=variable,y=value,color=index_f,group=index_f)) +geom_point()+ geom_line()
```